### PR TITLE
ENG-1013 allow absolute paths

### PR DESCRIPTION
**Pull request by annieshin**
I noticed we were doing importing with a lot of double dots (`../`s). Example:  `import actions from '../../../../src/activity/redux/actions';`

A train of double dots can make refactoring, reading, and maintenance difficult, so I would like to propose that we use absolute paths. `import actions from 'activity/redux/actions';`

I don't know if backend wants to do this so I added it to only front-end.js in this PR. This must go in before any changes to frontend code changes that use absolute paths vs relative paths. Dashboard PR: https://github.com/neednova/dashboard/pull/381

If we don't add this, we'll see these eslint issues for example when using absolute paths:
screen shot 2018-05-07 at 8 23 14 am

### CODE REVIEW

**Comment by mds4mstuke** [comment]
loves abs imports -- we should consider on backend too @neednova/engineering

**Comment by palderson** [comment]
I'd love to import abs. It would make things at the gym so much easier.

**Comment by kevinjsuh** [comment]
In

**Comment by x5a** [comment]
also okay with this

**Comment by annieshin** [comment]
should i move it to common.js then?

**Comment by juecd** [comment]
Super down for this to be part of backend too!

**Pull request merged**
